workspace:
  base: /go

pipeline:
  build:
    image: teracy/ubuntu:14.04-dind
    environment:
      - GO15VENDOREXPERIMENT=1
    commands:
      - docker version
      - docker-compose version
    privileged: true

service:
  postgres:
    image: postgres:9.4.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo
